### ISSUE TITLE
for x86 ?

### ISSUE THREAD

**Issue by Barisakd2163** [AlSch092/UltimateAntiCheat#16]

**Comment by AlSch092** [comment]
Many techniques won't work for x86 (particularly on Wow64, as the majority of us are using 64-bit OS) such as process handle gathering, and remapping sections. I do have an x86 static library version, but will not be posting it publically as someone on here wasted my time and tried to scam me for doing this work for them without paying (and thus posting it publically would be giving them what they wanted for free). Also, I found the majority of people asking for x86 wanted it so that they could use it for stolen code/illegal private servers, which is explicitly prohibited in the GNU-Affero license and breaks copyright laws. Sorry for the inconvenience.
