### ISSUE TITLE
Why aren't you checking CAT signatures?

### ISSUE THREAD

**Issue by ghost** [AlSch092/UltimateAntiCheat#6]
Hi,

I have been reading and testing your Anti-Cheat and was confused about how it complained that almost everything in my C:\ drive and all of the loaded modules were invalid.

I did some digging, and inside of Integrity.cpp you have a function VerifyEmbeddedSignature of namespace Authenticode, however nothing for catalog signatures which is what windows verifies drivers/DLLs with. I also saw that in class Integrity, you push KERNEL32 and other windows DLLs to the WhitelistedModules list implying that they were throwing errors too.

Is there a reason for not verifying catalog signatures?

**Comment by AlSch092** [comment]
Just haven't gotten around to it yet; as you can see it's only a basic call to WinVerifyTrust, and parts of that logic should definitely be re-written. Since test mode checks are already present, unsigned drivers shouldn't be a problem, and whitelisted modules should ideally be gathered in the TLS callback at program startup for later comparison. 

Kudos, if you feel as if there's parts that can be improved, you're of course welcome to fork and PR.

**Comment by AlSch092** [comment]
Call to `GetUnsignedDrivers` has been removed for now since no action was being taken on its results. The process of whitelisting loaded modules has been changed to being fetched in the TLS callback and later compared to, and any delta modules are checked via `WinVerifyTrust` + added to the whitelist if they're signed.

Testing on my machine shows the only 'unknown' loaded module in release build being 'uxtheme.dll', which is not signed and thus works as intended. Unsigned driver checks will be added back once I have some time to properly add catalog checking.

**Comment by ghost** [comment]
Hi sorry for late reply,

> The process of whitelisting loaded modules has been changed to being fetched in the TLS callback and later compared to

Could you not use Copy On Write detection?

> and any delta modules are checked via WinVerifyTrust 

You are not validating if WinVerifyTrust has been tampered with. If you hook CryptSIPVerifyIndirectData fake signatures can be passed off as real. Also, Ideally check if `SOFTWARE\\Microsoft\\Cryptography\\OID\\EncodingType 0\\CryptSIPDllVerifyIndirectData\\{C689AAB8-8E78-11D0-8C47-00C04FC295EE}` has been tampered with.

I could PR these changes if you'd like, but I'll stop talking in this thread.

**Comment by AlSch092** [comment]
Nice find! I appreciate the addition, registry entries are a vector I had not thought of. For anti-hooking I'm planning on making hashes of all whitelisted modules, since checking for hooks at specific offsets (function prologues for example) can of course be easily avoided. If you'd like to PR I can check over it and approve. I don't mind if you post here, email would also be okay. 

Cheers
