### ISSUE TITLE
License question

### ISSUE THREAD

**Issue by SystemDeezNuts** [AlSch092/UltimateAntiCheat#9]
Hello, Your project is very impressive and would be very useful to me, I write software released into the public domain. But the AGPL V3 license makes this impossible to use *in whole or in part* because you would almost definitely need to distribute the library along with any program that'd make use of it which means that the entire project would also need to be AGPL v3.

**Comment by AlSch092** [comment]
Greetings,

I specifically chose this license to prevent people from possibly rebranding & selling the project as their own work. Is your software going to be paid, or free? If the software you wanted to use this project in  doesn't make money, I might be able to explicitly give you permissions or add a clause to the license. Otherwise if you're planning on making money off this, I cannot approve such usage without royalties since I've worked on it for a while and gotten nothing from it.

Cheers

**Comment by orosbogdan** [comment]
Is this limited to just rebranding and selling the project. I want to use it in a small scale commercial game, would that be forbidden as well with the current license?

**Comment by AlSch092** [comment]
Hey Bogdan,

You can use it for your game, I give you explicit permission to use it for that purpose. If you're able to send me an email with the title or website of your game I'd appreciate it (just for bookkeeping sake, it won't be publically listed anywhere). Feel free to pull the project to your local machine and delete the license associated with it for usage in your project.

Cheers,
Al

**Comment by orosbogdan** [comment]
> Hey Bogdan,
> 
> You can use it for your game, I give you explicit permission to use it for that purpose. If you're able to send me an email with the title or website of your game I'd appreciate it (just for bookkeeping sake, it won't be publically listed anywhere). Feel free to pull the project to your local machine and delete the license associated with it for usage in your project.
> 
> Cheers, Al

Hey, I've sent you a mail on
aschwarz92@outlook.com

I've sent you some details regarding the company name for book keeping and possible renegociation if the project becomes succesful.

Thank you so much.
